### ISSUE TITLE
Initialisation - Description d'Aldo

### ISSUE THREAD

**Issue by martinregner** [datagir/aldo#1]
- Objectif : passer un outil Excel de calculer de stock de carbone des sols dans les territoires en format web
- Public : 
    - 700 "obligés" dans les collectivités (chargés de mission PCAET) ; au moins 1 fois par an
    - Peut intéresser au-delà : sans doute 1000 et même + (5 000 inscrits à un précédent webinaire sur la séquestration)
		
- Produit
	- saisir sa communes / son groupement de communes
	- Les surfaces pour les différents types de sols se remplissent automatiquement via appel aux bases de données
	- possible de corriger les surfaces + spécifier les pratiques agricoles par surfaces agricoles
	- Sortie :
		- Tableau de bord : graphes (les mettent ensuite dans leur rapport, soit image en direct soit en téléchargeant le fichier)
		- Export CSV, + pdf ?
   - Un outil de sensibilisation type "mon convertisseur CO2" pourrait être intéressant, sur un volet à part du simulateur (ou sur l'accueil, avant de rentrer ses données ?) : didactique, encourage les bonnes pratiques, permet de faire de la pédagogie y compris pour les chargés de missions auprès de leurs collègues / élus
   
- Planning : 
   - Fin d'année ?
   - Une conférence au SVC fin de novembre sur la séquestration
   - Une conférence possible à Genève aux Assises de la TE en janvier

**Comment by laem** [comment]
J'ai initié une fiche produit ici : https://pad.incubateur.net/BMbE5LX7QBmaYDw68nyBkw

N'hésitez pas à l'améliorer :)

**Comment by martinregner** [comment]
> Une adresse contact ?

Une assistance technique continue d'être dédiée à cet outil : aldo (at) associationbilancarbone.fr

> Back-office :
Est-il nécessaire d'avoir un BO administrable (donc avec connexion) ?
Comment seront intégrées les données ? En dur ? API ? Fréquence de modifications ?

Les données seront doute initialement toutes en dur mais ensuite en API, autant que possible.

A noter : certaines données (1 ou 2 jeux de données ; à clarifier avec l'ABC) sont **retravaillées par l'ABC** pour rendre la donnée brute adaptée à Aldo. Leur modification est sans doute au maximum annuelle --> proposition de modifier directement via Github dans un premier temps

**Comment by martinregner** [comment]
Pour une première version, l'équipe projet Aldo confirme l'intérêt de commencer par : 
- base CORINE Land Cover (CLC) 
- les stocks

> A noter : certaines données (1 ou 2 jeux de données ; à clarifier avec l'ABC) sont retravaillées par l'ABC pour rendre la donnée brute adaptée à Aldo. 

Aujourd'hui certaines données de stock à l'échelle de la commune ont été construites en partant des données à l'échelle des régions (pédo-climatiques), d'où un recalcul.
L'équipe projet propose plutôt pour le nouvel outil :
1. d'avoir en base les données par régions pédo-climatiques
2. de stocker la correspondances communes <> régions pédo-climatiques
3. de calculer directement les données communales depuis les données sources à l'échelle régionale

Cela parait plus pérenne (pour les mises à jours des données sources), léger (au moins en termes de bases de données), et évite de laisser croire que l'on a des données à l'échelle de la commune, qui ne sont en fait que des moyennes issues d'un niveau bien supérieur.
