### ISSUE TITLE
Choisir et brancher avec l'URL propre

### ISSUE THREAD

**Issue by hfroot** [datagir/aldo#13]
@martinregner, c'est à qui à décider l'URL ?

**Comment by martinregner** [comment]
Aujourd'hui tout est regroupé ici : https://www.territoires-climat.ademe.fr/

![image](https://user-images.githubusercontent.com/46482115/161543229-6b751229-8d2a-47e5-b98c-537876d83c3a.png)

Comme pour TACCT, on pourrait transformer le https://www.territoires-climat.ademe.fr/aldo en https://aldo.ademe.fr/
Le CTA deviendrait aussi "Accéder"

C'est à discuter avec Miriam lors d'un prochain point + produit

**Comment by hfroot** [comment]
https://aldo-carbone.ademe.fr/
