### ISSUE TITLE
Design front valeurs de stock + introduction

### ISSUE THREAD

**Issue by hfroot** [datagir/aldo#3]
Le début d'une maquette :

https://www.figma.com/file/vUVXzsv3UV7EeY4zlSIoKY/Aldo?node-id=1117%3A195656

Quelques questions vite-fait :

- Vous pensez quoi de suivre le design système d'état ?
- Quelles données sont le plus intéressant pour le graphique ?
- Est-ce qu'il y a des autres infos intéressantes du EPCI à mettre en avance sur cette page ? Population / département / région ?
- Rechercher par EPCI ou commune ?

**Comment by florianpanchout** [comment]
Je pense que c'est une bonne idée d'utiliser le DSE ici. C'est un outil pour des pros et pas destiné au grand public

**Comment by martinregner** [comment]
- Vous pensez quoi de suivre le design système d'état ?
   - Très bien !
- Quelles données sont le plus intéressant pour le graphique ?
   - pour les graphiques, je te propose dans un premier temps de reprendre les graphiques actuels de l'Excel :
   
![image](https://user-images.githubusercontent.com/46482115/152330155-20bfc0e4-4cee-4171-bf70-9d38d8c5d5b7.png)

- Est-ce qu'il y a des autres infos intéressantes du EPCI à mettre en avance sur cette page ? Population / département / région ?
   - ah oui, intéressant ! Des API pour aller chercher ce type d'info facilement ?
   - Afficher au moins Région / Département serait intéressant.
   - Bonne idée d'ajouter la population pour proposer des ratios de stock de C / hab. --> pour une prochaine version peut-être ?
- Rechercher par EPCI ou commune ?
   - Le résultat est plutôt attendu dans un premier temps par EPCI, qui est un groupement de communes. Cependant, il serait intéressant de pouvoir faire des regroupements de communes autres, par exemple pour des parcs nationaux. Les données étant au niveau commune (sans être pertinente à ce niveau là seulement, mais plutôt pour être agrégée) il faut dans tous les cas prévoir un mécanisme d'agrégation de plusieurs communes. Dans un premier temps, il est peut-être plus facile de "automatiquement" faire l'agrégation des communes d'un EPCI lorsque l'utilisateur en sélectionne un... qu'en penses-tu ?

**Comment by hfroot** [comment]
@martinregner merci pour tes commentaires.

J'ai noté que la population est inclue dans les données du tableur, et facilement retrouvable dans un library npm qui fournit la liste des communes/EPCI etc. Alors c'est assez facile d'afficher.

Je vais avoir la question de regroupement des communes en tête quand je travail pour que ça soit plus facile d'utiliser un autre façon hors d'EPCI.
