### ISSUE TITLE
Brancher Matomo

### ISSUE THREAD

**Issue by hfroot** [datagir/aldo#9]
@martinregner est-ce que matomo pourrait être intéressant pour le projet ?

**Comment by martinregner** [comment]
Tant qu'il n'y a pas de back cela peut être intéressant de suivre les connexions / le nombre d'utilisateurs. Il est possible qu'il y ait des parties sans back (ex. explication des FE...).
Plus globalement, cela peut permettre de suivre le temps de parcours.
Qu'en penses-tu ?

**Comment by hfroot** [comment]
Discuté dans une réu : On va utiliser Matomo pour le suivi de nombre d'utilisateurs

**Comment by hfroot** [comment]
Fait [d633065] - j'ai choisi matomo car c'est gratuit, bien connu chez datagir, et car il y a pas trop besoin d'avoir les stats super jolis ou en temps réel
